# Generated by Django 5.0.3 on 2024-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articulo_imagen_alter_articulo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
