# Generated by Django 5.0.3 on 2024-04-15 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_fecha_publicacion_comentario_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comentario_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
